// Record the conformance corpus: the file two interpreters have to agree on.
//
// Run it with `npm run build:conformance`. It plays seeded games through the
// TypeScript interpreter and writes down what happened. The Go interpreter then
// has to reproduce all of it, which is what turns "the two implementations
// agree" from an intention into a test.
//
// The recorder is one of the two implementations, so this file cannot prove the
// *rules* are right — that is the differential test's job, against the shipped
// modes whose answers are already known. What it proves is that the other
// implementation matches this one, everywhere the language goes.
//
// **A case is a game, not a position.** That is not for tidiness: threefold
// repetition depends on every position a game has been through, so a lone board
// cannot say whether the next move draws. Replaying from the opening reproduces
// that history for free, and costs less space than repeating a board per ply.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
  alphabetOf,
  createAnalysisGame,
  squareLabel,
  startingPositionFromGrid,
  type AnalysisGame,
} from '@/engine/analysisGame';
import { createSeededRandom } from '@/engine/bots/engine';
import { CORPUS_SPECS } from '@/engine/spec/conformance/specs';
import { modeDefinitionFor, specAllMoves, specApplyMove } from '@/engine/spec/interpret';
import type { Grid, Position } from '@/types/game';

// Boards are written as one string with ranks joined by "/" — the same shape
// `game.StartingPosition` stores in Go, and a quarter of the size of one JSON
// string per rank. Territory uses `r`, `b`, and `.` for unclaimed.
const territory = (grid: Grid) =>
  grid
    .map((row) =>
      row
        .map((tile) => (tile.ownerColor === 'Red' ? 'r' : tile.ownerColor === 'Blue' ? 'b' : '.'))
        .join(''),
    )
    .join('/');

const snapshot = (game: AnalysisGame) => ({
  rows: startingPositionFromGrid(game.grid, alphabetOf(game.mode)).rows.join('/'),
  territory: territory(game.grid),
  turn: game.currentTurn,
  moveNumber: game.moveNumber,
  status: game.status,
  winner: game.winner,
  endReason: game.endReason ?? null,
});

const moveName = (move: { from: Position; to: Position }) =>
  `${squareLabel(move.from)}-${squareLabel(move.to)}`;

interface Check {
  ply: number;
  /** Every legal move for the side to move, sorted and space-separated. */
  legalMoves: string;
  /** The position after the move at this ply. */
  after: ReturnType<typeof snapshot>;
}

interface Game {
  spec: string;
  seed: number;
  /** Space-separated, in order. Replay them from the spec's own opening. */
  moves: string;
  checks: Check[];
}

const PLY_LIMIT = 60;
const SEEDS = 4;
// Every position is played; every fourth is checked in detail. Consecutive plies
// of one game test almost the same thing, and the file is meant to be readable
// by a person when it fails.
const CHECK_EVERY = 4;

const games: Game[] = [];

for (const [name, spec] of Object.entries(CORPUS_SPECS)) {
  const mode = modeDefinitionFor(spec, `corpus-${name}`);
  for (let seed = 1; seed <= SEEDS; seed += 1) {
    const random = createSeededRandom(seed * 7919);
    let game = createAnalysisGame(mode);
    const moves: string[] = [];
    const checks: Check[] = [];
    for (let ply = 0; ply < PLY_LIMIT && game.status === 'InProgress'; ply += 1) {
      const legal = specAllMoves(spec, game);
      if (legal.length === 0) break;
      const chosen = legal[Math.floor(random() * legal.length)];
      if (!chosen) break;
      const played = specApplyMove(spec, game, chosen.from, chosen.to);
      if (!played) throw new Error(`${name} seed ${seed} ply ${ply}: ${moveName(chosen)} was refused`);
      moves.push(moveName(chosen));
      // Always check the last ply of a game: the endings are the part most
      // likely to drift, and skipping one because of its index would be exactly
      // the wrong economy.
      if (ply % CHECK_EVERY === 0 || played.game.status !== 'InProgress') {
        checks.push({
          ply,
          // Sorted, so two implementations that generate moves in different
          // orders still agree.
          legalMoves: legal.map(moveName).sort().join(' '),
          after: snapshot(played.game),
        });
      }
      game = played.game;
    }
    games.push({ spec: name, seed, moves: moves.join(' '), checks });
  }
}

const corpus = {
  corpus: 1,
  note: 'Generated by scripts/buildConformance.mts. Do not edit by hand.',
  specs: CORPUS_SPECS,
  games,
};

const target = join(process.cwd(), 'src', 'engine', 'spec', 'conformance', 'corpus.json');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${JSON.stringify(corpus, null, 2)}\n`);

const plies = games.reduce((total, game) => total + game.checks.length, 0);
const endings = games.filter((game) => game.checks.at(-1)?.after.status !== 'InProgress');
const reasons = new Set(endings.map((game) => game.checks.at(-1)?.after.endReason));
console.log(
  `wrote ${games.length} games over ${Object.keys(CORPUS_SPECS).length} specs, ` +
    `${plies} checked plies, ${endings.length} finished (${[...reasons].join(', ')})`,
);
