import { useEffect, useState } from 'react';
import { Linking, Platform, Pressable, Text, View } from 'react-native';

import { entriesFor, licenceCounts } from './licences';
import type { LicenceEntry, LicencesData } from './licences';
import { SOURCE_URL } from '@/navigation/links';
import { up } from '@/navigation/upFrom';
import { colors, contentWidth, radius, space, themedSheet, type } from '@/theme';
import BackLink from '@/ui/BackLink';
import ScreenShell from '@/ui/ScreenShell';
import { Badge, Panel } from '@/ui/primitives';

// Every third-party package this build ships, and its licence.
//
// Most of these licences ask for their notice to travel with every copy of the
// code, and the website and the App Store build are both copies. This page is
// where the notices travel.
//
// The list is generated by `npm run licences` from what the two builds actually
// ship: the source maps of a real export, plus the native code the iOS app
// links. It's loaded with `import()` rather than imported, so on the web its
// 150 KB of licence text is a chunk of its own instead of part of every page's
// bundle. On iOS the bundle is one file either way.

/** Android is not built yet, so everything that is not the web is the iOS list. */
const PLATFORM = Platform.OS === 'web' ? 'web' : 'ios';

const keyOf = (entry: LicenceEntry) => `${entry.name}@${entry.version ?? ''}`;

export default function LicencesScreen() {
  const [data, setData] = useState<LicencesData | null>(null);
  const [failed, setFailed] = useState(false);
  const [attempt, setAttempt] = useState(0);
  const [open, setOpen] = useState<ReadonlySet<string>>(() => new Set());

  // After the first render, never during it: the pre-rendered page has no list,
  // so the first client render must not have one either.
  useEffect(() => {
    let live = true;
    setFailed(false);
    import('./licences.json')
      .then((module) => {
        if (live) setData(module.default as unknown as LicencesData);
      })
      .catch(() => {
        if (live) setFailed(true);
      });
    return () => {
      live = false;
    };
  }, [attempt]);

  const toggle = (key: string) =>
    setOpen((current) => {
      const next = new Set(current);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });

  const entries = data ? entriesFor(data, PLATFORM) : [];
  const where = PLATFORM === 'web' ? 'This site' : 'This app';

  return (
    <ScreenShell width={contentWidth.reading}>
      <BackLink href={up.licences.href} label={up.licences.label} />

      <View style={styles.hero}>
        <Text style={styles.heroEyebrow}>OPEN SOURCE</Text>
        <Text style={styles.heroTitle}>Open-source licences</Text>
        <Text style={styles.heroSubtitle}>
          RPS Strategy is open source under the AGPL-3.0.{' '}
          <Text
            accessibilityRole="link"
            onPress={() => Linking.openURL(SOURCE_URL)}
            style={styles.inlineLink}
          >
            Read its source ↗
          </Text>
        </Text>
        <Text style={styles.body}>
          {data
            ? `${where} is also built on ${entries.length} packages, each under its own licence. Tap one to read it.`
            : `${where} is also built on packages by other people, each under its own licence.`}
        </Text>
        {data ? (
          <View style={styles.counts}>
            {licenceCounts(entries).map(({ licence, count }) => (
              <Badge key={licence} label={`${licence} · ${count}`} />
            ))}
          </View>
        ) : null}
      </View>

      {failed ? (
        <Panel>
          <Text style={styles.body}>The list didn't load. Check your connection and try again.</Text>
          <Pressable
            accessibilityRole="button"
            onPress={() => setAttempt((count) => count + 1)}
            style={({ pressed }) => [styles.retry, pressed && styles.pressed]}
          >
            <Text style={styles.retryLabel}>TRY AGAIN</Text>
          </Pressable>
        </Panel>
      ) : !data ? (
        <Panel>
          <Text style={styles.body}>Loading the list…</Text>
        </Panel>
      ) : (
        <Panel>
          {entries.map((entry, index) => (
            <PackageRow
              key={keyOf(entry)}
              data={data}
              divided={index > 0}
              entry={entry}
              expanded={open.has(keyOf(entry))}
              onToggle={() => toggle(keyOf(entry))}
            />
          ))}
        </Panel>
      )}
    </ScreenShell>
  );
}

interface PackageRowProps {
  data: LicencesData;
  entry: LicenceEntry;
  expanded: boolean;
  divided: boolean;
  onToggle: () => void;
}

function PackageRow({ data, entry, expanded, divided, onToggle }: PackageRowProps) {
  const detail = [entry.version, entry.url?.replace(/^https?:\/\//, '')].filter(Boolean).join(' · ');
  return (
    <View style={[styles.row, divided && styles.rowDivided]}>
      <Pressable
        accessibilityLabel={`${entry.name}, ${entry.licence}`}
        accessibilityRole="button"
        // Rather than `accessibilityState`, which react-native-web drops: this
        // one reaches VoiceOver on iOS and the DOM on the web.
        aria-expanded={expanded}
        onPress={onToggle}
        style={({ pressed }) => [styles.rowHeader, pressed && styles.pressed]}
      >
        {/* `minWidth: 0` so a long scoped name wraps instead of pushing the licence off the row. */}
        <View style={styles.rowCopy}>
          <Text style={styles.rowTitle}>{entry.name}</Text>
          {detail ? <Text style={styles.rowMeta}>{detail}</Text> : null}
        </View>
        <Badge label={entry.licence} />
        <Text style={styles.chevron}>{expanded ? '▾' : '▸'}</Text>
      </Pressable>
      {expanded ? (
        <View style={styles.rowBody}>
          {entry.note ? <Text style={styles.note}>{entry.note}</Text> : null}
          {entry.texts.map((index) => (
            <View key={index} style={styles.textBlock}>
              <Text selectable style={styles.licenceText}>
                {data.texts[index]}
              </Text>
            </View>
          ))}
          {entry.url ? (
            <Text
              accessibilityRole="link"
              onPress={() => Linking.openURL(entry.url!)}
              style={styles.inlineLink}
            >
              {entry.url} ↗
            </Text>
          ) : null}
        </View>
      ) : null}
    </View>
  );
}

const styles = themedSheet(() => ({
  // The same opening as the credits page this sits under.
  hero: { gap: space.small, paddingBottom: space.snug },
  heroEyebrow: { ...type.eyebrow, color: colors.accent, letterSpacing: 2.1 },
  heroTitle: {
    color: colors.textStrong,
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -1,
  },
  heroSubtitle: { ...type.bodyStrong, color: colors.textMuted, lineHeight: 20 },
  body: { ...type.bodyStrong, color: colors.textMuted, lineHeight: 19 },
  inlineLink: { color: colors.accentText, textDecorationLine: 'underline' },
  counts: { flexDirection: 'row', flexWrap: 'wrap', gap: space.tight },

  row: { paddingVertical: space.small },
  rowDivided: { borderTopWidth: 1, borderTopColor: colors.borderSoft },
  rowHeader: { flexDirection: 'row', alignItems: 'center', gap: space.small },
  rowCopy: { flex: 1, minWidth: 0, gap: space.hair },
  rowTitle: { ...type.rowTitle, color: colors.textStrong },
  rowMeta: { ...type.meta, color: colors.textFaint },
  chevron: { color: colors.textFaint, fontSize: 12, width: 12, textAlign: 'center' },
  rowBody: { gap: space.small, paddingTop: space.small },
  note: { ...type.body, color: colors.textMuted },
  textBlock: {
    backgroundColor: colors.surfaceWell,
    borderColor: colors.borderSoft,
    borderWidth: 1,
    borderRadius: radius.small,
    padding: 10,
  },
  licenceText: { color: colors.textSoft, fontFamily: 'monospace', fontSize: 10, lineHeight: 15 },

  retry: {
    alignSelf: 'flex-start',
    marginTop: space.small,
    paddingHorizontal: space.medium,
    paddingVertical: space.snug,
    borderRadius: radius.small,
    borderWidth: 1,
    borderColor: colors.border,
  },
  retryLabel: { ...type.label, color: colors.textStrong },
  pressed: { opacity: 0.7 },
}));
