// The shape of licenceData.json, and the two questions the licences page asks of it.
//
// The data is generated by `scripts/licences.mts` (`npm run licences`) from what
// the website and the iOS app actually ship. Kept apart from the screen so the
// test beside it can read the same types without a React transform.

export type Platform = 'ios' | 'web';

export interface LicenceEntry {
  name: string;
  /** Null for native code that has no npm package to take a version from. */
  version: string | null;
  /** As the package declares it: an SPDX expression, almost always. */
  licence: string;
  platforms: Platform[];
  url: string | null;
  /** The package's directory, relative to `frontend/`, when it came from npm. */
  from: string | null;
  /** Indexes into `texts`. Empty only if a package ships no licence and names nobody. */
  texts: number[];
  /** Where the text came from, when it is not the package's own licence file. */
  note: string | null;
  /** The generator's working field, removed before it writes the file. */
  author?: string | null;
}

export interface LicencesData {
  about: string;
  /** The React Native version the native part of the list was written against. */
  reactNative: string;
  packages: LicenceEntry[];
  /** Every distinct licence text once, since most packages share a handful. */
  texts: string[];
  /** Direct dependencies that ship in neither build, so their absence is deliberate. */
  notShipped: string[];
}

/** What this build ships. Android is not built yet; when it is, it gets its own pass. */
export const entriesFor = (data: LicencesData, platform: Platform): LicenceEntry[] =>
  data.packages.filter((entry) => entry.platforms.includes(platform));

/** How many packages each licence covers, most common first. */
export function licenceCounts(entries: LicenceEntry[]): { licence: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const entry of entries) counts.set(entry.licence, (counts.get(entry.licence) ?? 0) + 1);
  return [...counts]
    .map(([licence, count]) => ({ licence, count }))
    .sort((a, b) => b.count - a.count || a.licence.localeCompare(b.licence));
}
