// Generated by tools/generate-game-sounds.py. Do not edit by hand.
//
// One entry per pack: the peak envelope of its `moveSelf` clip, in
// 40 buckets across a shared 0.40s window, scaled so the
// loudest pack reaches 1. Shared axes are what make the shapes
// comparable — a pack that rings longer draws wider, and a pack that is
// quieter draws shorter, which is exactly what the picker should say.

export const SOUND_WAVEFORMS: Record<string, readonly number[]> = {
  wood: [0.905, 0.848, 0.584, 0.49, 0.288, 0.236, 0.158, 0.028, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  felt: [0.53, 0.511, 0.391, 0.25, 0.16, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  arcade: [1, 0.98, 0.787, 0.597, 0.458, 0.381, 0.324, 0.263, 0.209, 0.164, 0.129, 0.108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  glass: [0.666, 0.597, 0.554, 0.549, 0.537, 0.51, 0.476, 0.425, 0.396, 0.36, 0.321, 0.284, 0.271, 0.263, 0.251, 0.236, 0.22, 0.202, 0.177, 0.159, 0.142, 0.131, 0.126, 0.121, 0.114, 0.107, 0.099, 0.091, 0.083, 0.073, 0.066, 0.063, 0.06, 0.057, 0.053, 0.049, 0.021, 0, 0, 0],
};
