import { StyleSheet, Text, View } from 'react-native';

import { colors, contentWidth, radius, themedSheet } from '@/theme';
import ScreenShell from '@/ui/ScreenShell';
import { Panel, SectionHeading } from '@/ui/primitives';
import type { PanelTone } from '@/ui/tones';

export const LAST_UPDATED = 'September 24, 2026';
export const CONTACT_DISCORD = '@henhen1227';

// The policy text lives here as data rather than JSX so the screen body stays a
// single map and editing the wording never means touching layout. Mirrors
// PRIVACY.md at the repository root — change both together.
/** One block of the policy, as data so the screen body stays one map. */
interface PolicySection {
  eyebrow: string;
  title: string;
  tone?: PanelTone;
  paragraphs?: string[];
  /** Rendered as a list under the paragraphs. */
  bullets?: string[];
}

const sections: PolicySection[] = [
  {
    "eyebrow": "OVERVIEW",
    "title": "Every game is recorded",
    "tone": "accent",
    "paragraphs": [
      `RPS Strategy is run by Henhen1227, LLC, Henry's company, on a self-hosted server. This agreement is with the LLC, and “I” on this page means Henry Abrahamsen (${CONTACT_DISCORD}), acting for it. Online games are recorded and linked to your account. Play fairly and treat other players well.`
    ]
  },
  {
    "eyebrow": "STORED DATA",
    "title": "What I store",
    "paragraphs": [
      "Account: a random account ID generated by your browser, your username, and a SHA-256 hash of your local account key. The key itself is not stored.",
      "Discord sign-in: your Discord user ID and handle. The only permission requested is identify, so I cannot see your email, servers, or activity. You can revoke access in Discord under Authorised Apps.",
      "Older password accounts: a salted PBKDF2 password hash, removed when you link Discord. New accounts use Discord sign-in.",
      "Finished online games, kept indefinitely: both players, mode, result and reason, ranked status, ratings before and after, move count, time control, and start and finish times.",
      "Player totals: wins, losses, draws, games played, and a rating for each mode. Tournament records include your entry name, Discord handle, matches, and results.",
      "Feedback: posts, replies, votes, and your username when posting. Bug reports also include app version, platform, and any game you attach. This information is public."
    ]
  },
  {
    "eyebrow": "PUBLIC INFORMATION",
    "title": "What other players can see",
    "paragraphs": [
      "Your opponent and the lobby can see your username, Discord handle, rating, and record. Anyone can watch live games.",
      "Your opponent and spectators can read game chat. Chat stays in server memory during the game and is not saved to the database. Other players can still take screenshots.",
      "Messages and usernames containing listed slurs or strong profanity are rejected. Use reports for anything the filter misses.",
      "Anyone can read the feedback board. Posting, replying, and voting require a Discord-verified account. Posts carry your username and remain public until deleted. Delete your own posts from the post menu, or ask me to remove them.",
      "Keep account problems and other private information off the board. Use reports or contact me directly."
    ]
  },
  {
    "eyebrow": "PLAYER SAFETY",
    "title": "Reporting and blocking",
    "paragraphs": [
      "Report or block a player from the ⋯ menu in chat or from their profile.",
      "Reports include the recent conversation. I review them within 24 hours and may mute, restrict, or remove an account. Anyone can report, including guests. You will not receive an outcome update.",
      "Your block list is private. Blocking hides messages in both directions and prevents direct challenges. Matchmaking can still pair you. Sign in to block players, and manage your list under Your account → Blocked players."
    ]
  },
  {
    "eyebrow": "PUBLISHED DAILY",
    "title": "The public game archive",
    "paragraphs": [
      "Finished games are published daily on Hugging Face for research and to let others check opening statistics.",
      "Exports include moves and clock readings, mode, result and reason, ranked status, ratings before and after, time control, and start and finish times. Games finished from September 9, 2026 onward include both usernames.",
      "Exports exclude Discord IDs and handles, account IDs, account key hashes, password hashes, IP addresses, and chat. An opaque player key groups games without revealing the underlying account ID.",
      "Games finished before September 9, 2026 use “Anonymous player” for both names.",
      "Published files may already have been downloaded and cannot be recalled. Renaming your account changes future exports only. Contact me to exclude your name from future files."
    ]
  },
  {
    "eyebrow": "DATA USE",
    "title": "What I do not do",
    "paragraphs": [
      "No ads, analytics SDKs, trackers, or data sales. The public game archive is the only data shared. Only I can access the database. Web-server logs record IP addresses for operation and debugging, separately from game records."
    ]
  },
  {
    "eyebrow": "ACCOUNT CONTROL",
    "title": "Deleting your account",
    "paragraphs": [
      "Choose Delete account at the bottom of your account page and type your username to confirm. Deletion is immediate and permanent.",
      "Your username, Discord link, titles, leaderboard entry, and sign-in are removed. Your bots are retired. Accounts with no finished games are deleted outright.",
      "Finished games stay to preserve opponents’ records and ratings. Your name becomes “Deleted player” in game records, the archive, and saved move lists.",
      "Feedback posts and replies keep their text under “Deleted player”. Your votes are removed. To remove a post entirely, delete it before deleting your account, or ask me.",
      "Future public archive exports use the deleted name. Previously published files may still contain your old name and cannot be recalled.",
      `If deletion fails, contact me on Discord (${CONTACT_DISCORD}) for help.`,
      "Clearing browser data removes your local account key. Discord sign-in restores a linked account. Without a linked account, losing that key means losing access."
    ]
  },
  {
    "eyebrow": "ONLINE PLAY AGREEMENT",
    "title": "Rules for online play",
    "bullets": [
      "No harassment, slurs, threats, or bigotry in chat, usernames, or Discord handles.",
      "Play your own games. No engines, bots, or outside help during live play. Use analysis before or after a game.",
      "Do not rig results, throw games, sandbag, or use alternate accounts to dodge opponents or inflate ratings.",
      "Do not stall or leave a game to avoid a loss.",
      "Do not exploit bugs, scrape, or flood the server. Report bugs you find.",
      "Violations may lead to voided games, reset ratings, or account removal. There is no formal appeal process; contact me to discuss a decision."
    ]
  },
  {
    "eyebrow": "UPDATES",
    "title": "Changes and contact",
    "paragraphs": [
      "I update this page and its date when the policy changes. Continuing to play means you agree to the current version.",
      `Post bugs and suggestions under You → Feedback. For private questions or problems reports cannot resolve, contact ${CONTACT_DISCORD} on Discord.`
    ]
  }
];

// No back button: this is a row of the You group, and it lights up. See the
// longer note on the credits page, which carried the same one for the same
// reason and lost it for the same reason.
export default function PolicyScreen() {
  return (
    <ScreenShell width={contentWidth.reading}>
      <>
          <View style={styles.hero}>
            <Text style={styles.eyebrow}>THE HOUSE RULES</Text>
            <Text style={styles.title}>Privacy & play</Text>
            <Text style={styles.subtitle}>Last updated {LAST_UPDATED}</Text>
          </View>

          <View style={styles.stack}>
            {sections.map((section) => (
              <Panel key={section.title} tone={section.tone ?? 'default'}>
                <SectionHeading eyebrow={section.eyebrow} title={section.title} />
                {section.paragraphs?.map((paragraph) => (
                  <Text key={paragraph} style={styles.body}>
                    {paragraph}
                  </Text>
                ))}
                {section.bullets && (
                  <View style={styles.bulletList}>
                    {section.bullets.map((bullet) => (
                      <View key={bullet} style={styles.bulletRow}>
                        <Text style={styles.bulletMark}>◆</Text>
                        <Text style={styles.bulletText}>{bullet}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </Panel>
            ))}
          </View>
      </>
    </ScreenShell>
  );
}

const styles = themedSheet(() => ({

  // Nothing above it to clear now. See the same style on the credits page.
  hero: { paddingBottom: 22 },
  eyebrow: { color: colors.accent, fontSize: 10, fontWeight: '900', letterSpacing: 2.1 },
  title: {
    color: colors.textStrong,
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -1,
    marginTop: 5,
  },
  subtitle: { color: colors.textMuted, fontSize: 13, lineHeight: 20, marginTop: 6 },

  stack: { gap: 12 },
  body: { color: colors.textMuted, fontSize: 12, lineHeight: 19, marginTop: 10 },

  bulletList: { gap: 9, marginTop: 13 },
  bulletRow: {
    flexDirection: 'row',
    gap: 9,
    paddingVertical: 9,
    paddingHorizontal: 11,
    borderRadius: radius.medium,
    backgroundColor: colors.surfaceMuted,
  },
  bulletMark: { color: colors.accentBright, fontSize: 9, lineHeight: 19 },
  bulletText: { flex: 1, color: colors.text, fontSize: 12, lineHeight: 19 },

  pressed: { opacity: 0.7 },
}));
